### PR TITLE
DropDown component

### PR DESCRIPTION
**Pull request by sethen**
Continuation of PR at https://github.com/Insightpool/orchestra/pull/13 -- no idea why Github API closed this.

### CODE REVIEW

**Comment by colbydehart** [comment]
👍

**Comment by sethen** [comment]
Actually want to change the `onChange` to `onSelect` ... Seems more appropriate.

**Comment by colbydehart** [comment]
I just called it `onChange` because that is what the callback is called for a `<select>` element, which is what the dropdown is most similar to: [React docs](https://facebook.github.io/react/docs/forms.html#interactive-props).

But it matters very, very, little to me. Want me to make the change?

**Comment by sethen** [comment]
I changed the `items` to `options` and changed some other wording... Other than that, gg.

**Pull request merged**
